title: GhostMoon
author: borfei
theme: ghostmoon

url: "https://borfei.github.io"
baseurl: "ghostmoon"

nav:
  - title: "Demo"
    url: "/"
  - title: "Playground"
    url: "/playground"
  - title: "About"
    url: "/about"
